### ISSUE TITLE
Discussion about preStart event and how to achieve it

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#105]
While working on odo issue https://github.com/openshift/odo/issues/3565, I read the events lifecycle parent issue https://github.com/devfile/kubernetes-api/issues/32, and noticed that we haven't discussed a few points in there.

I think we need to have a discussion before `preStart` is implemented, so that a devfile achieves the same functionality in odo and Che.

 Acc to the schema, `preStart` has a description:
```
"Names of commands that should be executed before the workspace start. Kubernetes-wise, these commands would typically be executed in init containers of the workspace POD."
```

I have a few questions here if we want to run these events as init containers.

- Are `preStart` events' component external as raised here https://github.com/devfile/kubernetes-api/issues/32#issuecomment-614117176. I see the conversation went from an `external` property to the existing `dedicatedPod` property. Can `preStart` event components be used by the application pod or will they always be init containers?
- If `preStart` events' components cannot be used in application pod, shouldn't the `preStart` event command be void of group kind ie; they cannot have `build`/`run`/`debug`/`test`
- In the OP https://github.com/devfile/kubernetes-api/issues/32#issue-586983211, there is a statement
```
Commands associated to the same lifecycleBinding are not guarantee to be executed sequentially or in any order. To run commands in a given order a user should use a composite.
```

but init containers dont execute in parallel. They are executed sequentially before the next init container can run - https://kubernetes.io/docs/concepts/workloads/pods/init-containers/. 
- What is the expected behaviour if I use this edge case composite command in my `preStart` event?
```
components:
  - container:
      name: "tools2"
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      memoryLimit: 1024Mi
      mountSources: true
  - container:
      name: "tools"
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      mountSources: true
      memoryLimit: 1024Mi
commands:
  - exec:
      id: myPreStart
      commandLine: echo I am a myPreStart
      component: tools
      workingDir: /
  - exec:
      id: myPreStart2
      commandLine: echo I am a myPreStart2
      component: tools
      workingDir: /
  - exec:
      id: secondPreStart
      commandLine: echo I am also a secondPreStart
      component: tools2
      workingDir: /
  - composite:
         id: mycompevent
         label: my composite cmd
         commands:
           - myPreStart2
           - secondPreStart
         parallel: true
         group:
          kind: build
          isDefault: true
events:
  preStart:
    - "myPreStart" 
    - "mycompevent"
```

will I need two init containers for the component `tools`? If you notice the composite command has `myPreStart2` which references `tools` and the other preStart command `myPreStart` also references `tools`. What is the use of the flag `parallel` in here, extending the argument about init containers dont execute in parallel
- And finally the biggest question IMO, how are we expected to execute these commands in init containers? Init containers should always complete before the application pod is started. How do we guarantee execution of `preStart` event commands in init containers, if init containers use the image's default entrypoint(Kubernetes's container command & args). We cant use `tail -f /dev/null` as init containers must complete before the application pod is started. Does each `preStart` command become the entry point of an init container?

**Comment by kadel** [comment]
> * Can `preStart` event components be used by the application pod or will they always be init containers?

I'm not sure what you mean.
Maybe something like this?
```yaml
components:
  - container:
      name: "tools"
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      mountSources: true
      memoryLimit: 1024Mi
commands:
  - exec:
      id: build
      component: tools
  - exec:
      id: myPreStart
      component: tools

events:
  preStart:
    - "myPreStart" 
```
This is perfectly valid. The initContainer will be defined in a same way as a "main" container.






> * In the OP [#32 (comment)](https://github.com/devfile/kubernetes-api/issues/32#issue-586983211), there is a statement
> 
> ```
> Commands associated to the same lifecycleBinding are not guarantee to be executed sequentially or in any order. To run commands in a given order a user should use a composite.
> ```
> 
> but init containers dont execute in parallel. They are executed sequentially before the next init container can run - https://kubernetes.io/docs/concepts/workloads/pods/init-containers/.

"are not guaranteed" doesn't mean that they can't be executed sequentially. Executing them sequentially is ok.






> * What is the expected behaviour if I use this edge case composite command in my `preStart` event?

Composite commands are just troubles :-/ 
I think that the only solution is to expand composite commands into a sequence of normal commands.
this 
```yaml
  - composite:
         id: mycompevent
         label: my composite cmd
         commands:
           - myPreStart2
           - secondPreStart
         parallel: true
         group:
          kind: build
          isDefault: true
events:
  preStart:
    - "myPreStart" 
    - "mycompevent"
```

would become equivalent to
```yaml
events:
  preStart:
    - "myPreStart" 
    - "myPreStart2"
    - "secondPreStart"
```
The downside of this is that it won't execute in parallel as defined in composite commands. But I don't think to see a reasonable solution on how to execute commands in parallel especially considering that each command in composite command can use a different container. 


> * And finally the biggest question IMO, how are we expected to execute these commands in init containers? Init containers should always complete before the application pod is started. How do we guarantee execution of `preStart` event commands in init containers, if init containers use the image's default entrypoint(Kubernetes's container command & args). We cant use `tail -f /dev/null` as init containers must complete before the application pod is started. Does each `preStart` command become the entry point of an init container?


In order to for initContainers to work properly, we need sets `command` in `containerSpec` for to a command defined in the devfile command.
For example, for something like this
```yaml
components:
  - container:
      name: "tools"
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
commands:
  - exec:
      id: myPreStart
      commandLine: echo I am a myPreStart
      component: tools
      workingDir: /
events:
  preStart:
    - "myPreStart" 
```
the initContainer could look something like this
```yaml
initContainers:
    - name: myPreStart:
      command: ["sh", "-c", "cd / && echo I am a myPreStart"]
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
```

command would be constructed using this template: `sh -c 'cd $workingDir && $commandLine'`

**Comment by maysunfaisal** [comment]
> > * Can `preStart` event components be used by the application pod or will they always be init containers?
> 
> I'm not sure what you mean.
> Maybe something like this?
> 
> ```yaml
> components:
>   - container:
>       name: "tools"
>       image: quay.io/eclipse/che-nodejs10-ubi:nightly
>       mountSources: true
>       memoryLimit: 1024Mi
> commands:
>   - exec:
>       id: build
>       component: tools
>   - exec:
>       id: myPreStart
>       component: tools
> 
> events:
>   preStart:
>     - "myPreStart" 
> ```
> 
> This is perfectly valid. The initContainer will be defined in a same way as a "main" container.
> 


@kadel acc to the original issue https://github.com/devfile/kubernetes-api/issues/32, this is not how it is to be used. The `tools` component cannot be used by both event and command. At least that is how the discussion went, I am not sure how we're enforcing this or if its upto Che/Odo to implement the validation.


> 
> Composite commands are just troubles :-/
> I think that the only solution is to expand composite commands into a sequence of normal commands.
> this
> 
> ```yaml
>   - composite:
>          id: mycompevent
>          label: my composite cmd
>          commands:
>            - myPreStart2
>            - secondPreStart
>          parallel: true
>          group:
>           kind: build
>           isDefault: true
> events:
>   preStart:
>     - "myPreStart" 
>     - "mycompevent"
> ```
> 
> would become equivalent to
> 
> ```yaml
> events:
>   preStart:
>     - "myPreStart" 
>     - "myPreStart2"
>     - "secondPreStart"
> ```
> 
> The downside of this is that it won't execute in parallel as defined in composite commands. But I don't think to see a reasonable solution on how to execute commands in parallel especially considering that each command in composite command can use a different container.
> 

So it looks like we need to spin up two init containers for the component `tools` in this example since `myPreStart` and `myPreStart2` references it?

 
> In order to for initContainers to work properly, we need sets `command` in `containerSpec` for to a command defined in the devfile command.
> For example, for something like this
> 
> ```yaml
> components:
>   - container:
>       name: "tools"
>       image: quay.io/eclipse/che-nodejs10-ubi:nightly
> commands:
>   - exec:
>       id: myPreStart
>       commandLine: echo I am a myPreStart
>       component: tools
>       workingDir: /
> events:
>   preStart:
>     - "myPreStart" 
> ```
> 
> the initContainer could look something like this
> 
> ```yaml
> initContainers:
>     - name: myPreStart:
>       command: ["sh", "-c", "cd / && echo I am a myPreStart"]
>       image: quay.io/eclipse/che-nodejs10-ubi:nightly
> ```
> 
> command would be constructed using this template: `sh -c 'cd $workingDir && $commandLine'`

Yeah that was assumption going into this work as well. So that means, we are overriding the image's default command & args. What happens if someone provides command(`[some-command]`) and args(`[-f, some-args]`) in the container component for a `preStart` event like this:
```
components:
  - container:
      name: tools
      image: maysunfaisal/springbootbuild
      memoryLimit: 768Mi
      command: ['some-command']
      args: [ '-f', 'some-args']
      mountSources: true
      volumeMounts:
        - name: springbootpvc2
          path: /data
```
We should override it acc to our discussion with the event commands like you suggested `["sh", "-c", "cd / && echo I am a myPreStart"]` but should we document this difference in  behaviour between a container used by events and used by the application itself?
