### ISSUE TITLE
Devfile Registry should provide the stack/sample associated files & artifacts

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1073]
/kind user-story

## Which area this user story is related to?

/area library
/area registry

## User Story

As a devfile registry user, I would like to access the files & artifacts associated with a Devfile stack/sample hosted on the Devfile Registry.

For example, let us consider this [Quarkus Sample Devfile](https://github.com/devfile-samples/devfile-sample-code-with-quarkus/blob/main/devfile.yaml), it has  the following Kubernetes component:

```yaml
- name: kubernetes-deploy
    attributes:
      deployment/replicas: 1
      deployment/cpuLimit: '100m'
      deployment/cpuRequest: 10m
      deployment/memoryLimit: 250Mi
      deployment/memoryRequest: 100Mi
      deployment/container-port: 8081
    kubernetes:
      uri: deploy.yaml
      endpoints:
        - name: http-8081
          targetPort: 8081
          path: /
```

While the file `deploy.yaml` is available in the GitHub repository [here](https://github.com/devfile-samples/devfile-sample-code-with-quarkus/blob/main/deploy.yaml) as expected, the same file should be available on the Devfile Registry. To further clarify, the above Devfile is available on the Devfile Registry [here](https://registry.devfile.io/devfiles/code-with-quarkus) but there is no `deploy.yaml` file at the expected location like https://registry.devfile.io/devfiles/deploy.yaml

This situation also applies to any other files or artifacts that are hosted on the repository and whose relative path is mentioned in the Devfile. Currently, [application-service](https://github.com/redhat-appstudio/application-service) works around this issue by using the raw Github link like https://raw.githubusercontent.com/devfile-samples/devfile-sample-code-with-quarkus/main/deploy.yaml instead of a Devfile Registry URL.

## Acceptance Criteria

- [ ] All the files and artifacts hosted on a stack/sample Github repository and referenced relative in the Devfile should be hosted on the Devfile Registry
- [ ] The hosted file path should be well thought out, because Devfile stacks have versions
- [ ] The hosted file path should also account for the exact relative path as specified in the Devfile i.e.; if a file is available at `/my/path/deploy.yaml` in the Devfile then the file should be hosted at `/my/path`
- [ ] Devfile is currently hosted at https://registry.devfile.io/devfiles/code-with-quarkus, so we need to think about how the files and artifacts would be available as an endpoint after also taking versioning into consideration
