### ISSUE TITLE
Dependent Projects

### ISSUE THREAD

**Issue by l0rd** [devfile/api#1082]
## Which area this feature is related to?

/area api

## Which functionality do you think we should add?

Introduce a new field, `dependentProjects` in the Devfile spec.

**Why is this needed? Is your feature request related to a problem?**

The devfile is supposed to be versioned in the application git repository. This same git repository will be cloned when the dev environment defined in the devfile is started.

But what if developers need to clone other repositories to be able to build a and test the application.

To include in a workspace the sources from other git repositories (or zip files) we can introduce a new field, `dependentProjects` in the Devfile spec. That would allow cloning repositories other than the one where the devfile is located.

**Detailed description:**

In the following example, the devfile of the backend service references the source code of the frontend with the `dependentProjects` field. As a result the source code of the frontend will be included in the cloud development environment:

```yaml
schemaVersion: 2.2.0
metadata:
  name: backend
dependentProjects:
  - name: frontend
    git:
      remotes:
        origin: https://github.com/myorg/frontend.git
      checkoutFrom:
        revision: main
components:
  - name: devtools
    container:
      (...)  
```
