### ISSUE TITLE
Need to fix version `v1alpha1` of devfile API

### ISSUE THREAD

**Issue by amisevsk** [devfile/api#111]
### Is your feature request related to a problem? Please describe.
Recent discussions around issues such as https://github.com/devfile/api/issues/102 has brought forward the realization that we haven't actually fixed the devfile spec for `v1alpha1` and it is still possible to merge breaking changes there. This is an issue because this API is already consumed by the devworkspace operator and the [OpenShift console](https://github.com/openshift/console/blob/7ebee46c10e96b61f016f8c354bc8a8b6ac9cea7/frontend/packages/console-app/src/components/cloud-shell/cloud-shell-utils.ts#L39-L66), though this usage is a fairly minimal subset of the spec:

```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha1
metadata:
  name: web-terminal
  annotations:
    controller.devfile.io/restricted-access: "true"
  labels:
    console.openshift.io/terminal: "true"
spec:
  started: true
  routingClass: 'web-terminal'
  template:
    components:
      - plugin:
          name: web-terminal
          id: redhat-developer/web-terminal/4.5.0
```
Having conflicting specs with the `workspace.devfile.io/v1alpha1/DevWorkspace` GVK will make it impossible to use `v1alpha1`, and any breaking changes that aren't compatible with the yaml above will break the devworkspace operator in a way that's not easily fixed, since it likely isn't possible to migrate between specs within the same GVK.

### Describe the solution you'd like
We need to fix `v1alpha1` as soon as possible, and push any not-backwards-compatible changes to a `v1alpha2` or `v1beta1` version instead.
