### ISSUE TITLE
Add dependency check for current child samples

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1142]
## Which area/kind this issue is related to?

/area ci
/area registry

## Issue Description

In order to ensure our current child samples remain compatible with changes to their parent stacks, a dependency check on these samples will be necessary to prevent breaking changes from being introduced to the parents. This dependency check should be run on all PRs made to the [community registry repository](https://github.com/devfile/registry).

We need to:
1. Set up a dependency tree that shows the current child samples for each parent stack
2. Triggers the testing of child samples as part of the PR tests of the parent stacks

The auto-generated dependency tree and inclusion of additional child stacks/samples are planned in the upcoming #1060 changes.

## Target Odo version

N/A

**Comment by michael-valdron** [comment]
Targeting this issue for next sprint to focus on higher prior items.

**Comment by michael-valdron** [comment]
For the parent stack dependency tree we can use a parents yaml file which could be built from a script that runs nightly.

Proposed parents file:

```yaml
parents:
  stack1_name:
    children:
      - name: child1_name
      - name: child2_name
        version: 1.0.2
  stack2_name:
    version: 1.1.0
    children:
      - name: child3_name
```
