### ISSUE TITLE
Align devfile usage between tools

### ISSUE THREAD

**Issue by ehsavoie** [devfile/api#1144]
## Which area this feature is related to?

/area api

## Which functionality do you think we should add?

Currently I need to provide a devfile that is specific to the tool I'm going to use (in my case odo vs devspaces). This is related to the fact that both environment are quite different and that I need to have my devfile adapt to that (as opposed to have the tools being able to provide the same functionality adapted to their respective environment).

**Why is this needed? Is your feature request related to a problem?**

**Detailed description:**

You can find for example the devfiles on https://github.com/wildfly-extras/wildfly-devfile-examples (use the odo and devspaces branches).
I split the inner loop and outer loop on devspaces in several steps to be able to demonstrate what we need to do in a tutorial.

**Comment by feloy** [comment]
# Non-terminating commands

```
--- devfile-devspaces.yaml
+++ devfile-odo.yaml
     container:
-      image: quay.io/wildfly/wildfly-s2i:latest 
-      #This command is there to avoid crashloop 
-      command: ['sleep', 'infinity']
+      image: quay.io/wildfly/wildfly-s2i:latest
```

This command is added for Devspaces because the image defined in the Devfile has a terminating command. See https://github.com/devfile/registry/pull/102. 

# Composite commands

```
# Doesn't work until https://github.com/eclipse/che/issues/21859 is fixed.
  - id: outer-loop
    composite:
      label: "20-Build and deploy the application on OpenShift."
      commands:
        - openshift-build
        - openshift-registry-login
        - build-runtime-image
        - push-image
        - deploy-image
      group:
        kind: deploy
        isDefault: false
      parallel: false
```

Currently, VS Code editor in Che doesn't support the Devfile Composite Commands. See https://github.com/eclipse/che/issues/21859

# Deploy

Deploy is handled differently in odo and in DevSpaces.

- odo: Build Image + Deploy Kubernetes manifest
- devspaces: exec command to execute Helm commands

# Build / Run commands

- odo can run only one Build and ond Run command, automatically, using a specific lifecyle. 
- In DevSpaces, the user can run any defined command at any time
