### ISSUE TITLE
Release triggered workflows for registry operator

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1282]
## Which area/kind this issue is related to?

/area ci
/area registry
/area releng

## Issue Description

Registry operator releases should produce built images on quay.io for use of the releases.

Guide to creating release workflows: https://birtony.medium.com/setting-up-automated-release-workflow-with-github-actions-628dbca2446e

**Release Workflow Trigger Example**
```
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
```

## Acceptance Criteria

- [ ] Create a workflow file that triggers on release cuts
- [ ] Create tasks to build and push `quay.io/devfile/registry-operator` and `quay.io/devfile/registry-operator-bundle` on the release changes, use version label as tag
- [ ] Perform integration testing on release images
