### ISSUE TITLE
Quarkus stack fails to pass odov2 and odov3 checks

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1293]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area ci
/area registry
/area test-automation

## Bug Summary

The checks for [PR#225](https://github.com/devfile/registry/pull/225) are failing for both `odo v2` and `odo v3` stack validation. As you can see in [this error trace from odov3](https://github.com/devfile/registry/actions/runs/6483831705/job/17707463213?pr=225) the issue comes from error: http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError

**Describe the bug:**

During the tests, when we try to build quarkus starter project, the maven project cannot be built as during the build process the container runs out of memory (Java heap space).

**To Reproduce:**

In order to reproduce this locally you can try to run the `check_odov2.sh`:
```
$ cd tests/odov3
$ stackDirs="java-quarkus"
$ currentPath="$(pwd)"
$ stacksPath="$(pwd)/../../stacks"
$ ginkgo run --procs 2 -v -trace --slow-spec-threshold 120s   --timeout 2h   $currentPath -- -stacksPath $stacksPath -stackDirs "$stackDirs"
```

## Expected behavior

The quarkus application should be built successfully

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

ci check: https://github.com/devfile/registry/actions/runs/6483831705/job/17707463213?pr=225

## Additional context

N/A

### Any workaround?

I've tried increasing the memory limit of `java-quarkus` devfile and it worked locally:

### Suggestion on how to fix the bug

In `stacks/java-quarkus/devfile.yaml`:
```
components:
  - name: tools
    container:
      image: registry.access.redhat.com/ubi8/openjdk-17:1.17-1.1696520325
      args: ['tail', '-f', '/dev/null']
      memoryLimit: 1024Mi # instead of 512Mi
```
