### ISSUE TITLE
Exec command should make component required

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#152]
Currently the spec does not define the component in an exec as required. I am wondering if that's the case, what is the point in have an exec command at all? If the there is an exec command in a devfile, it is to be executed in a container; which is to be represented by the component property.

https://github.com/devfile/api/blob/master/pkg/apis/workspaces/v1alpha2/commands.go#L125

**Comment by davidfestal** [comment]
@l0rd wdyt about this one ? It seems we should make the component mandatory right ?

**Comment by elsony** [comment]
I don't see much usage on a command without a component. Without the component info, the tools using the devfile won't know where are they going to execute the command.

**Comment by l0rd** [comment]
Agreed. The component should be mandatory for exec commands. On the other hand apply commands should not require that.

**Comment by mmulholla** [comment]
So this:

	// Describes component to which given action relates
	// +optional
	Component string `json:"component,omitempty"`

Becomes:

	// Describes component to which given action relates
	// 
	Component string `json:"component"`

?????

**Comment by davidfestal** [comment]
Yes, exactly.

**Comment by johnmcollier** [comment]
So, I think this is a good idea. But one thing I'm wondering is, will this cause issues for overriding parent commands in devfiles if the component isn't specified?

E.g.
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
parent:
  uri: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml
  commands:
    - id: install
      exec:
        commandLine: npm install && echo hi
```

Is currently valid, and changes the `commandLine` for the `install` command. But, will it still be valid if we make `component` required?
