### ISSUE TITLE
Python v3.0.0 and Spring Boot stack sample doesn't show composite commands in Eclipse Che

### ISSUE THREAD

**Issue by dmytro-ndp** [devfile/api#1524]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

Eclipse Che Next (7.85.0-SNAPSHOT)
Dev Spaces 3.12.0 deployed to workspaces.openshift.com

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**

When I create workspace using devfile https://github.com/devfile/registry/blob/main/stacks/python/3.0.0/devfile.yaml Eclipse Che 7.85.0 / Dev Spaces 3.12.0, I see no composite commands `build-image`, `deployk8s` in the devfile task list in VS Code editor: 
```
  - id: build-image
    apply:
      component: build
  - id: deployk8s
    apply:
      component: deploy
  - id: deploy
    composite:
      commands:
        - build-image
        - deployk8s
      group:
        kind: deploy
        isDefault: true
```

**To Reproduce:**

1. Create and open workspace on DevSandbox using the link https://workspaces.openshift.com/#/https://raw.githubusercontent.com/devfile/registry/main/stacks/python/3.0.0/devfile.yaml
2. Go to **top left menu > Terminal > Run Task...**
3. Open list of devfile commands.

There are only 3 commands in the list:
- devfile: run-app
- devfile: pip-install-requirements
- devfile: debug-py
![Screenshot from 2024-04-16 15-48-36](https://github.com/devfile/api/assets/1197777/87e62654-f7e3-4991-b67f-4f56a0cad054)

## Expected behavior
Task list includes next composite commands described in the https://github.com/devfile/registry/blob/main/stacks/python/3.0.0/devfile.yaml:
- devfile: run-app
- devfile: pip-install-requirements
- devfile: debug-py
- **devfile: build-image**
- **devfile: deployk8s**
