### ISSUE TITLE
Spring Boot v2.1.0 stack sample doesn't show composite commands in Eclipse Che

### ISSUE THREAD

**Issue by dmytro-ndp** [devfile/api#1526]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

Eclipse Che Next (7.85.0-SNAPSHOT)
Dev Spaces 3.12.0 deployed to workspaces.openshift.com

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**

When I created workspace using devfile https://github.com/devfile/registry/blob/main/stacks/java-springboot/2.1.0/devfile.yaml in Eclipse Che 7.85.0 / Dev Spaces 3.12.0, I saw no composite commands `build-image`, `deployk8s` in the devfile task list in VS Code editor: 
```
  - id: build-image
    apply:
      component: build
  - id: deployk8s
    apply:
      component: deploy
  - id: deploy
    composite:
      commands:
        - build-image
        - deployk8s
      group:
        kind: deploy
        isDefault: true
```

**To Reproduce:**

1. Create and open workspace on DevSandbox using the link https://workspaces.openshift.com/#/https://raw.githubusercontent.com/devfile/registry/main/stacks/java-springboot/2.1.0/devfile.yaml
2. Go to **top left menu > Terminal > Run Task...**
3. Open list of devfile commands.

There are only 3 commands in the list:
- devfile: build
- devfile: run
- devfile: debug

## Expected behavior
Task list includes next composite commands described in the https://github.com/devfile/registry/blob/main/stacks/java-springboot/2.1.0/devfile.yaml:
- devfile: build
- devfile: run
- devfile: debug
- **devfile: build-image**
- **devfile: deployk8s**

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable
![Screenshot from 2024-04-16 18-11-15](https://github.com/devfile/api/assets/1197777/5bb72056-e6c9-471d-9564-e0eb78abe25b)
