### ISSUE TITLE
Error logged with Quarkus stacks related to LogManager

### ISSUE THREAD

**Issue by apupier** [devfile/api#1612]
/kind bug

### Which area is this bug related to?

/area registry

### Go project

**Operating System and version:**

**Go Pkg Version:**

### Node.js project

**Operating System and version:**

**Node.js version:**

**Yarn version:**

**Project.json:**

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**

There is an error stacktrace logged with Quarkus examples

**To Reproduce:**

## Expected behavior

no error in log

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

```
commands:
- exec:
    commandLine: ./mvnw -Dmaven.repo.local=/home/user/.m2/repository compile
    component: tools
    workingDir: ${PROJECT_SOURCE}
  id: init-compile
- exec:
    commandLine: ./mvnw -Dmaven.repo.local=/home/user/.m2/repository quarkus:dev -Dquarkus.http.host=0.0.0.0
      -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    component: tools
    group:
      isDefault: true
      kind: run
    hotReloadCapable: true
    workingDir: ${PROJECT_SOURCE}
  id: dev-run
- exec:
    commandLine: ./mvnw -Dmaven.repo.local=/home/user/.m2/repository quarkus:dev -Dquarkus.http.host=0.0.0.0
      -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Ddebug=${DEBUG_PORT}
    component: tools
    group:
      isDefault: true
      kind: debug
    hotReloadCapable: true
    workingDir: ${PROJECT_SOURCE}
  id: dev-debug
components:
- container:
    args:
    - tail
    - -f
    - /dev/null
    endpoints:
    - name: https-quarkus
      protocol: https
      targetPort: 8080
    - exposure: none
      name: debug
      targetPort: 5858
    env:
    - name: DEBUG_PORT
      value: "5858"
    image: registry.access.redhat.com/ubi8/openjdk-21:1.19-1
    memoryLimit: 1024Mi
    mountSources: true
    volumeMounts:
    - name: m2
      path: /home/user/.m2
  name: tools
- name: m2
  volume:
    size: 3Gi
events:
  postStart:
  - init-compile
metadata:
  description: Java application using Quarkus and OpenJDK 21
  displayName: Quarkus Java
  icon: https://design.jboss.org/quarkus/logo/final/SVG/quarkus_icon_rgb_default.svg
  language: Java
  name: community
  projectType: Quarkus
  tags:
  - Java
  - Quarkus
  version: 1.5.0
  website: https://quarkus.io
schemaVersion: 2.2.0
starterProjects:
- name: community
  zip:
    location: https://code.quarkus.io/d?e=io.quarkus%3Aquarkus-resteasy&e=io.quarkus%3Aquarkus-micrometer&e=io.quarkus%3Aquarkus-smallrye-health&e=io.quarkus%3Aquarkus-openshift&cn=devfile&j=21
- name: redhat-product
  zip:
    location: https://code.quarkus.redhat.com/d?e=io.quarkus%3Aquarkus-resteasy&e=io.quarkus%3Aquarkus-smallrye-health&e=io.quarkus%3Aquarkus-openshift&j=21
```

```
tools: Could not load Logmanager "org.jboss.logmanager.LogManager"
tools: java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
tools:  at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
tools:  at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:225)
tools:  at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:210)
tools:  at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:205)
tools:  at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)
tools:  at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)
tools:  at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
tools:  at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:222)
tools:  at java.logging/java.util.logging.Logger.demandLogger(Logger.java:650)
tools:  at java.logging/java.util.logging.Logger.getLogger(Logger.java:720)
tools:  at java.logging/java.util.logging.Logger.getLogger(Logger.java:703)
tools:  at com.google.inject.internal.util.ContinuousStopwatch.<init>(ContinuousStopwatch.java:32)
tools:  at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:64)
tools:  at com.google.inject.Guice.createInjector(Guice.java:87)
tools:  at com.google.inject.Guice.createInjector(Guice.java:69)
tools:  at com.google.inject.Guice.createInjector(Guice.java:59)
tools:  at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:482)
tools:  at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:207)
tools:  at org.apache.maven.cli.MavenCli.container(MavenCli.java:646)
tools:  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:275)
tools:  at org.apache.maven.cli.MavenCli.main(MavenCli.java:204)
tools:  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tools:  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tools:  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
tools:  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
tools:  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
tools:  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
tools:  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tools:  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tools:  at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:52)
tools:  at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:161)
tools:  at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:73)
```

## Additional context

specific logger is part fo the comand line `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` but it is not part of the classpath.
It was added with this commit https://github.com/devfile/registry/commit/c44bfe2803fd3b3b6dfd782eb5ba0720ec24121f

@johnmcollier Do you remind why it was added?

### Any workaround?

remove the `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` from the devfile

### Suggestion on how to fix the bug

remove the `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` from the devfile
