### ISSUE TITLE
Define the devfile 2.0 equivalent of the Devfile 1.0 `chePlugin` `preferences`

### ISSUE THREAD

**Issue by davidfestal** [devfile/api#170]
**Is your feature request related to a problem? Please describe.**

In Devfile 1.0, there is a way to define preferences for a plugin.

> A plugin may need to be precisely tuned and in such case plugin preferences should be used. Example shows how jvm may be configured with plugin’s preferences.
>
>
```yaml
...
- id: redhat/java/0.38.0
  type: chePlugin
  preferences:
     java.jdt.ls.vmargs: '-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication'
```

cf. also Che documentation: https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_tuning_cheplugin_component_configuration

**Describe the solution you'd like**

We need to be sure that the Devfile 2.0.0 specification allows to express the equivalent concept, so that the use of Devfile 2.0 in Che will not loose a feature.

We should ensure this before the 2.0.0 Devfile spec release
