### ISSUE TITLE
Add the ability to configure volume implementation

### ISSUE THREAD

**Issue by sleshchenko** [devfile/api#189]
**Is your feature request related to a problem? Please describe.**
Default volume implementation should be like PVC, but there are cases for other types, like emptyDir.
Empty dir case: some containers need to bring some binaries to others. For Che has a remote plugin launcher binary that is propagated to sidecars.

**Describe the solution you'd like**
It addition to size we can define backend:
```yaml
components:
  - name: remote-injector
    volume:
      size: 100Mib
      emptyDir: {}
```

**Describe alternatives you've considered**
¯\_(ツ)_/¯

Maybe something like Che has
```yaml
components:
  - name: remote-injector
    volume:
      size: 100Mib
      temporary: true
```

**Additional context**
