### ISSUE TITLE
On startup automatically execute actions with initContainers components

### ISSUE THREAD

**Issue by l0rd** [devfile/api#20]
The traditional way of customizing an existing container image is to create a new container by extending that existing container as a parent image. For example, the java-maven dev file uses quay.io/eclipse/che-java11-maven:nightly to pull in Maven, rather than using the standard Maven docker image (hub.docker.com/_/maven).

However, this approach requires creating a ‘child’ image for every parent image that is to be used in Che (or at least those requiring customization).

This ‘nice to have’ feature proposes a second option for customizing containers: when a container is initially created in Che (from a devfile), files that are specified by an environment value can be automatically copied (on startup) into the container at specific locations using an `initContainer` component. 

As proposed, a devfile writer is free to either create parent image, or to customize an existing image using an `initContainer`. This feature is not a replacement, it is just another tool in the devfile-writers arsenal, to make it easier to customize individual files/directories in container without fully extending them with a new image.

Example

```yaml
components:
- container:
    image: maven:3.6.3-jdk-11
    volumeMounts:
    - name: scripts
      mountPath: "/home/user/scripts"
- initContainer:
  name: cp
  image: quay.io/devfile/cp"
  volumeMounts:
      - name: scripts
        mountPath: "/scripts"
  env:
      - name: SRC_PATHS
        value: "/src/resources/scripts/build.sh, /scripts2"
      - name: DEST_PATHS
        value: "/scripts, /scripts"
- volume:
    name: scripts
    emptyDir: {}
```

In this example, the container will be based on the standard maven image, but additional an additional script file (build.sh) and an additional directory (/scripts2) will be copied into the container at startup.

The source for both of these files would be the root of the project sources (where the devfile is located). 

For example: If the dev file were hosted [here](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/devfile.yaml) then build.sh would be hosted [here](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/resources/scripts/build.sh)

```yaml
<repo root>
    ├── devfile.yaml
    ├── scripts2
    └── resources
        └── scripts
            └── build.sh
````

With this feature, it is now possible to use an existing container image in Che, while still retaining the ability to add additional required files.
