### ISSUE TITLE
Ambiguity over exec & apply commands for preStart & postStop

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#204]
There is a semantic difference between exec and apply commands and when one should use them. For example,
- exec commands are commands that are required to be executed only when a container is up and running.
- apply commands are commands that are typically applied for example during preStart and postStop events, when a pod is not present.

However, having personally worked on Odo's preStart feature, this is not the case. Odo currently utilizes only exec and composite commands in its product. This is the case for preStart as well, where a preStart event is an exec command. The container component's command & args(image's command & args if the devfile container command & args are absent) are overridden by the exec command's  `commandLine` &  `workingDir`.

This is different to what the authors of the spec initially intended. The apply command's container component image command & args are to be used as preStart or postStop commands.

Having mentioned that, there is a use-case where we can utilize an exec command for preStart/postStop when the `dedicatedPod` in the container component is set to true. This use case can be useful and valid when a separate pod is required to that of the main pod. The dedicated pod can utilize the pvc volumes defined to execute its preStart & postStop actions whose data could be accessed by the main pod via the pvc volumes.

**Comment by elsony** [comment]
Agree with the proposed behaviour and need to update the schema description to describe this behaviour. Add a restriction to not allow using `dedicatedPod` with `preStart/postStop`.

**Comment by maysunfaisal** [comment]
@l0rd @davidfestal Can a composite command have apply commands as sub-commands? If yes, can the composite command be used as a preStart/postStop event.. Though it `parallel` property would not work in case of preStart as initContainers are executed sequentially always.

**Comment by elsony** [comment]
We probably should try to avoid making the logic too "smart". If our rule is to only allow apply command to be specified as the preStart/postStop command (not exec), then a composite command can only be used only if all of the containing commands are apply commands. If the composite command happens to contains a mix of exec and apply, then that command cannot be used as preStart/postStop command and it should fail in our validation.

**Comment by l0rd** [comment]
agree with @elsony

**Comment by kadel** [comment]
This is getting way too complicated.
In the current description for `preStart` we are saying that on Kubernetes `preStart` is implemented as initContainer. But `apply` command can reference for example `kubernetes` component.

```yaml
schemaVersion: 2.0.0
metadata:
  name: fail
  version: 1.0.0
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
  - name: asdf
    kubernetes:
      inlined: >
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: hello
        spec:
          template:
            spec:
              containers:
              - name: hello
                image: busybox
                command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
              restartPolicy: OnFailure
  - name: m2
    volume: {}
commands:
  - id: asdf
    apply:
      component: asdf

events:
  preStart:
    - asdf
```
Now, this doesn't make sense at all.
We need to create additional restrictions on what component types can be used with `apply` in `preStart`. Only `container` component should probably be allowed.
