### ISSUE TITLE
Support External Dependencies in DevFile & Che Workspace

### ISSUE THREAD

**Issue by triceam** [devfile/api#28]
Feature request: A mechanism to define/access external dependencies in the workspace.  This would consist of links to external dependencies so that a developer could easily access those dependencies directly from the context of the workspace.

External dependencies could be url links to any resouce on the web.  Common uses that I foresee are:
- links to Cloud services
- links to on-prem services
- links to related code repos
- links to project wikis
- links to deployments on other clusters

Proposed `externalDependency` component definition in the `defile.yaml`:

```yaml
apiVersion: 1.0.0
metadata:
  name: My-Workspace
projects:
  - name: My-App
    source:
      location: 'https://github.com/triceam/my-sample-app-repo'
      type: git
components:
  - id: che-incubator/typescript/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3000
    memoryLimit: 512Mi
    type: dockerimage
    alias: nodejs
    image: 'quay.io/eclipse/che-nodejs10-ubi:7.8.0'
  - name: IBM Watson Visual Recognition
    url: http://cloud.ibm.com/watson/instance
    type: externalDependency
  - name: IBM Cloud Continuous Delivery
    url: http://cloud.ibm.com/devops/instance
    type: externalDependency
  - name: My on-prem Database
    url: http://url.to.my.database/foo
    type: externalDependency
  - name: My on-prem OpenShift cluster
    url: http://url.to.my.openshift/dashboard
    type: externalDependency
```

Proposed visualization in the Eclipse Che workspace:
![image](https://user-images.githubusercontent.com/974294/74763566-08653a80-524e-11ea-80dc-7c5fad9b2d60.png)

Clicking on the external dependency link would open a new tab or window to access the external dependency.

**Comment by davidfestal** [comment]
I assume that, in the current `2.0.0` syntax of components (as first proposed on `master`, and discussed [here](https://github.com/che-incubator/devworkspace-api/issues/4) ), the current proposal would be written:
```yaml
...
components:
  - chePlugin:
      ...
  - container:
      ...
  - externalDependency:
      name: IBM Watson Visual Recognition
      url: http://cloud.ibm.com/watson/instance
  - externalDependency:
      name: IBM Cloud Continuous Delivery
      url: http://cloud.ibm.com/devops/instance
  - externalDependency:
      name: My on-prem Database
      url: http://url.to.my.database/foo
  - externalDependency:
      name: My on-prem OpenShift cluster
      url: http://url.to.my.openshift/dashboard
...
```
