### ISSUE TITLE
Parameter support for starter projects to generate tailored sample applications

### ISSUE THREAD

**Issue by elsony** [devfile/api#316]
The existing `starterProjects` support only supports static project generation, i.e. only a git, GitHub, or zip location can be specified to create an already-made application. In some cases,  a stack may want to make sure a generator to generate the starter project. In that case, devfile needs to be able to reference a generator and allows tools to pass in specific parameters that are required to generate a tailored starter project. 

Proposal:
One easy pattern that we can target is if the generator is already exposed as an URL. The existing `starterProjects` already supports different ways of creating `starterProjects`, e.g. git, GitHub, and zip. We can introduce a new method of `starterProjects` called generator with parameter support.
```
starterProjects:
  - name: nodejs-starter
    generator:
      url: "https://my.node.generator.address/generate"
      parameters:
        - id: param1
           label: userFriendlyLabel1
        - id: param2
           label: userFriendlyLabel2
```
userFriendlyLabel1 and userFriendlyLabel2 are user-friendly labels that the tools can use to prompt the user for the value of the parameters as needed.

When the tools call the generator to generate the sample application, this URL will be used:
https://my.node.generator.address/generate?param1=value1&param2&value2
