### ISSUE TITLE
Duplicate top level devfile objects

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#317]
**Describe the bug**
If there are duplicate top level devfile objects, the schema does not stop it. Is there an option in the schema to validate against this or is this expected to be validated outside the schema? 🤔 

**To Reproduce**
have a duplicate devfile top level obj like component and schema validation does not fail:
```
components:
- name: runtime1
  container:
    image: registry.access.redhat.com/ubi8/nodejs-12:1-45
components:
- name: runtime2
  container:
    image: registry.access.redhat.com/ubi8/nodejs-12:1-45
```

**Expected behavior**
should error out saying the components has been duplicated
