### ISSUE TITLE
Run exec commands as specified user

### ISSUE THREAD

**Issue by groeges** [devfile/api#34]
When running exec commands from a devFile within a container we may need to run the commands as a different user to the user that is the default user within the container. I am therefore proposing we have a `runAsUser` within the `exec`, for example:
```
commands:
  - exec:
      id: init-deps
      name: init image dependancies
      component: java-openliberty-build
      commandLine: /project/bin/init-stack.sh
      runAsUser: root 
 - exec:
      id: stack-prep
      name: stack-prep
      component: java-openliberty-build
      commandLine: /project/bin/run-stack.sh prep
      runAsUser: java_user 
  - composite:
      id: setupContainer
      commands:
        - init-deps
        - stack-prep
      parallel: false
      group:
        name: init
        isDefault: true
```
So in this example there is a need to run some setup that requires to be run as `root`, and then some other setup that needs to be run as `java_user`. 

It is not easy to switch userids within a shell script (bash) then different shell scripts need to be run and need to be run as different userids.
