### ISSUE TITLE
Name component type "manifest" instead "kubernetes" or "openshift"

### ISSUE THREAD

**Issue by l0rd** [devfile/api#36]
This a simple proposal to use the name `manifest` instead of `kubernetes` or `openshift` in the devfile components.

```yaml
---
components:
  - container:
        name: component1
        image: maven
  - manifest:
        name: component2
       reference: https://.../mongo.yaml
  - plugin:
        id: java
```
