### ISSUE TITLE
Devfile metadata: add a link to an external website

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#38]
When you use a devfile in an IDE, the IDE might want to be able to display a devfile-specific welcome page. Likewise, a command line tool might want to link to information on how to use the devfile. In both of these cases we want the devfile to provide the link and not pull other files into the user's project, which could be easily removed or annoying to clean up.

For cases like these it would be nice to have an optional doc url in the devfile metadata.

**Comment by l0rd** [comment]
We are going to add the `website` metadata at the top level of the devfile:

```yaml
---
schemaVersion: 2.0.0
metadata:
  name: quarkus-stack
  description: ...
  website: https://quarkus.io
```
