### ISSUE TITLE
Root folders for projects

### ISSUE THREAD

**Issue by sunix** [devfile/api#385]
**Is your feature request related to a problem? Please describe.**
At the moment, the devfile declares `projects` that are usually git projects. These git projects are actually git repository. In these git repos, it happens that projects to be loaded in an IDE are actually located in subfolders of the git repo.

For instance: https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app should have `node-frontend` and `quarkus-backend` loaded as `Project` (Eclipse IDE terminology) or `Workspace root` (VSCode/Theia/Che terminology).

These `projects` or `roots` should be concidered and defined in the devfile.

**Describe the solution you'd like**
From https://github.com/eclipse/che/issues/15347 (adapted to devfile 2)

Each projects defined in a workspace, would possibly have a list of folder that would be workspace roots of the Che workspace. `/projects` is the default one.

```yaml
projects:

  - name: che-quarkus-demo
    git:
      location: 'https://github.com/sunix/che-quarkus-demo'
      branch: microservices
    roots: ['quarkus-backend', 'node-frontend']

  - name: nodejs-ex
    git:
      location: 'https://github.com/sclorg/nodejs-ex'

  - name: nodejs-ex-sunix
    git:
      location: 'https://github.com/sunix/nodejs-ex'
    roots: []
```
would add the 3 folders `/projects/nodejs-ex`, `/projects/che-quarkus-demo/quarkus-backend`, `/projects/che-quarkus-demo/node-frontend` as workspace root.

Of course if the user is using the command `Add folder to workspace`, the devfile of the workspace would need to be updated.

`/projects/nodejs-ex-sunix` is not added as a workspace root because of it has `roots` array empty.
`/projects/nodejs-ex` is added as a workspace root because it is the default behaviour if no `roots` element is defined.

```yaml
  - name: nodejs-ex
    git:
      location: 'https://github.com/sclorg/nodejs-ex'
```
would be similar to 
```yaml
  - name: nodejs-ex
    git:
      location: 'https://github.com/sclorg/nodejs-ex'
    roots: ['.']
```

**Describe alternatives you've considered**
Using sparseCheckoutDirs, but user may want to keep the whole. sparseCheckoutDirs is useful for examples/samples repositories.

**Additional context**

**Comment by benoitf** [comment]
Hi Sun, what is the difference with https://github.com/eclipse/che/issues/15347 ?

**Comment by sunix** [comment]
I would prefer to have that part of the devfile schema

**Comment by l0rd** [comment]
@sunix what's the use case for the empty project root:

```yaml
  - name: nodejs-ex-sunix
    git:
      location: 'https://github.com/sunix/nodejs-ex'
    roots: []
```

The project gets cloned in `/projects/` but the IDE ignores it?

**Comment by sunix** [comment]
@l0rd yes. It should not happen very often, but it is to clarify the behavior if it happens.

**Comment by l0rd** [comment]
I would not supporting this use case (maybe with an attribute?).

And when `roots` is not specified I would expect be equivalent to `roots=[]` and therefore to correspond to the top folder to be the workspace root.

Another comment is that having both `roots` and `sparseCheckoutDir` is confusing from a user point of view. I would add to this proposal the deprecation of `sparseChekoutDir`.

**Comment by sunix** [comment]
> I would not supporting this use case (maybe with an attribute?).
> 
> And when `roots` is not specified I would expect be equivalent to `roots=[]` and therefore to correspond to the top folder to be the workspace root.

OK

I don't think we should deprecate `sparseCheckoutDir`: these are doing different things and could be used together or not.
For git projects, `sparseCheckoutDir` is git related and maybe used for different reasons. `roots` would be related to the structure of your project.
- `roots` could be used for git projects with several components: for instance a git project with `node-fronend` folder and another `quarkus-backend` folder.
- `sparseCheckoutDir` are usually used in sample repos, where we want just to clone/retrieve a subfolder. For instance https://github.com/quarkusio/quarkus-quickstarts, we would want to clone only 1 folder.

**Comment by benoitf** [comment]
I think that for quarkus-quickstarts we mainly want to see one project in the IDE but having other quickstarts there could be helpful as well as you may want to open them
I also think it was a workaround waiting to have proper multi-root workspaces support.

**Comment by elsony** [comment]
1. Remove `sparseCheckoutDir` from spec since we don't find a good use case for it.
2. `roots` will be a Che specific attribute since it is mostly for the UI

**Comment by sunix** [comment]
I am surprise that odo wouldn't use these kind of meta informations about projects/roots. For git repos that contain several projects in subfolders, this is a generic way to tell where the projects are.
In project like https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app, how would odo or che or eclipse or intellij know that the frontend is to be built from `node-frontend` and the backend from `quarkus-backend`?

**Comment by yangcao77** [comment]
@kadel Does Odo care about the project subfolders? The entire git repo will be cloned including the subfolders.

**Comment by kadel** [comment]
> In project like https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app, how would odo or che or eclipse or intellij know that the frontend is to be built from `node-frontend` and the backend from `quarkus-backend`?

Why complicate it with roots?
I can simply have something like this


``` yaml
projects:
  - name: quarkus-reactjs
    git:
      location: 'https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app'


commands:
  - id: build-frontend
    exec:
      component: nodejs
      commandLine: "npm install"
      workingDir: ${PROJECTS_ROOT}/node-frontend
  - id: build-backend
    exec:
      component: java
      commandLine: "mvn package"
      workingDir: ${PROJECTS_ROOT}/quarkus-backend
```
Then I can go further and even create a composite command to build both.
```yaml
  - id: build-all
    composite:
      commands:
        - build-frontend
        - build-backend
      group:
        kind: run
        isDefault: true
```
