### ISSUE TITLE
Stacks/Devfile matching rules

### ISSUE THREAD

**Issue by elsony** [devfile/api#40]
In a devfile that is being used to define a stack, there are certain files that the stack may be looking for to decide if a given project can be run by a given stack or not, e.g. a maven stack may look for the pom.xml and a node.js stack may look for package.json.

If we can provide a way to allow a given stack to define those required resources, we can use it in tools like Che or odo to do quick check on project to suggest the stacks on a devfile repo that may support the a given application.  An example can be:

```yaml
parent.yaml
---
schemaVersion: 2.0.0
metadata:
  publisher: my-org
  name: maven-stack
  version: x.y.z
  matchingRules:
    existingFiles: ['pom.xml', 'aaa.xml']
```

```yaml
devfile.yaml
---
schemaVersion: 2.0.0
metadata:
  name: my-maven-project
parent:
  id: organization/maven-stack/x.y.z
...
```

There may be other types other than `existingFiles` that we can support in the future.
