### ISSUE TITLE
Devfile registry index should have schema version

### ISSUE THREAD

**Issue by kadel** [devfile/api#400]
Currently, the devfile registry index is just a plain array.

```yaml
[
  {
    "name": "java-maven",
    "displayName": "Maven Java",
    "description": "Upstream Maven and OpenJDK 11",
    "tags": ["Java", "Maven"],
    "projectType": "maven",
    "language": "java",
    "links": { "self": "/devfiles/java-maven/devfile.yaml" },
  },
  {
    "name": "java-openliberty",
    "displayName": "Open Liberty",
    "description": "Open Liberty microservice in Java",
    "projectType": "docker",
    "language": "java",
    "links": { "self": "/devfiles/java-openliberty/devfile.yaml" },
  },
]
```

It might be good to attach some metadata on top of it, like for example `schemaVersion` similarly to what devfile has.

```yaml
{
  schemaVersion: "1.0.0",
  stacks:
    [
      {
        "name": "java-maven",
        "displayName": "Maven Java",
        "description": "Upstream Maven and OpenJDK 11",
        "tags": ["Java", "Maven"],
        "projectType": "maven",
        "language": "java",
        "links": { "self": "/devfiles/java-maven/devfile.yaml" },
      },
      {
        "name": "java-openliberty",
        "displayName": "Open Liberty",
        "description": "Open Liberty microservice in Java",
        "projectType": "docker",
        "language": "java",
        "links": { "self": "/devfiles/java-openliberty/devfile.yaml" },
      },
    ],
}

```

This will be especially handy in case where we need to change the index json schema and the library will have to keep supporting new and old schema.
