### ISSUE TITLE
white space in variable substitutions

### ISSUE THREAD

**Issue by kadel** [devfile/api#500]
Trailing and leading spaces in variables should not matter.

Currently If I have something like this:
```yaml
schemaVersion: 2.1.0
metadata:
  name: test
variables:
  VARIABLE_TEST: bar
components:
  - name: test
      env:
        - name: "FOO"
          value: "{{ VALUE_TEST }}"
```
it is invalid due to spaces before `}}` and after `{{`.
It would be good if the leading and trailing whitespace were ignored.
