### ISSUE TITLE
Misc. comments on outer-loop proposal 

### ISSUE THREAD

**Issue by scottkurz** [devfile/api#517]
/area api
(sorry not sure how to best label this)

## 1. 

As mentioned in the Google doc [comment](https://docs.google.com/document/d/1SL3ZJyAy8lp973EzQpY36VjTJHoyGXl2zUXokPiXwK8/edit?disco=AAAAMOZ5JA0), the syntax
```yaml
        attributes: 
          - name: CONTAINER_IMAGE
            value: {{myimage}}
```
wouldn't allow Devfile variable substitution, it would need to be more like:
```yaml
        attributes: 
          - CONTAINER_IMAGE: {{myimage}}
```

### suggestion

If 'attributes' generally refer to free-form YAML, in devfile, a better name might be **deployVariables**:

```yaml
        deployVariables: 
          - CONTAINER_IMAGE: {{myimage}}
```

### 2. 

In the example in https://github.com/devfile/api/blob/main/docs/proposals/devfile/outer-loop-build-and-deploy.md#example-of-kubernetes-deployment-manifest with:
```yaml
      spec:
        containers:
          - name: {{.COMPONENT_NAME}}
            image: {{.CONTAINER_IMAGE}}
            ports:
              - name: http
                containerPort: {{.PORT}}
                protocol: TCP
```
it is clear that `{{.CONTAINER_IMAGE}}` comes from the `CONTAINER_IMAGE` attribute on the deploy command.  But what about `{{.COMPONENT_NAME}}` and `{{.PORT}}` ?  Are these supposed to be other attrs not shown in the example snippet?  Are they more like "built-ins"?  Do they imply other Go template or Helm template functionality? Are they generically "derived" from other devfile structures ?    A lot could be read into that ;)

### 3.

For the image build, I assume the "args" representing any and all options e.g. to `docker build`, not just `--build-arg` options?  

E.g. I might have this:
```yaml
          dockerfile:
            buildContext: ${PROJECTS_ROOT}/build
            location: https://github.com/redhat-developer/devfile-sample/blob/master/src/Dockerfile
            args: [ "--build-arg", "arg1", "--label", "L1" ]
```

It seems tempting to maybe pick some options, like "label" and "promote" them into yaml... but I'm not sure how we decide which, so maybe not.

### 4.

What do we envision the composite command including both an image build and a deploy to look like?  I'm thinking it's a separate deploy command, which let's say is the default deploy command, e.g. maybe something like this:

```yaml

    components:
      - name: myk8sdeploy
        kubernetes:
          uri: deploy/deployment-manifest.yaml

    commands:
      - id: deployapply
        apply:
          component: myk8sdeploy
          group:
              kind: deploy
              isDefault: false
        attributes: 
          - name: CONTAINER_IMAGE
            value: {{myimage}}
      - id: build-and-deploy
        composite:
            commands:
              - deploybuild  # not shown, from earlier example
              - deployapply
            group:
                kind: deploy
                isDefault: true
            parallel: false
```

## Alternative suggestion

1. The use case where I primarily want to do an outer loop image build and deploy, and never care to just automatically build the image on "start" seems a bit verbose.

What if we disable the auto build on start with a new `autoBuild: false` property and add a new "imageComponent" property to reference the image component as a kind of "dependency" ? 

So something like:

```yaml

    components:
      - name: mydockerfileimage
        image:
          imageName: {{myimage}}
          autoBuild: false     # new property to turn off auto build (assuming it's still defaulted to true)
          dockerfile:
              location: Dockerfile
            
    components:
      - name: myk8sdeploy
        kubernetes:
          uri: deploy/deployment-manifest.yaml

    commands:
      - id: deployk8s
        apply:
          component: myk8sdeploy
          group:
            kind: deploy
            isDefault: true
       imageComponent:   mydockerfileimage
       deployVariables:           # if 'attributes' are generally free-form, it's confusing to have string types only here:
          - CONTAINER_IMAGE: {{myimage}}         # incorporating the other change
```

I feel like using a composite command adds some verbosity without being any conceptually clearer.   (It is already kind of a less-than-perfect fit I think to have this image component which looks like a command).   

If we're just inventing a new type of deploy command can't we say that its scope bridges multiple components?
