### ISSUE TITLE
Introduce new component 'podTemplate'

### ISSUE THREAD

**Issue by sbose78** [devfile/api#52]
As a stack author, I wish to provide outer-loop deployment guidance in the form of a podTemplate. The tools may offer different choices based on that : pod, Deployment, KnativeService, StatefulSet, DeploymentConfig, etc.

```
---
components:
  -  id: deploy-node-app
     podTemplate:
        containers:
          - command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600'] 
             readinessProbe:
               httpGet: ""
               path: /api/health/readiness
               port: 8080
               scheme: HTTP
```

When associated with the corresponding build guidance ( example https://github.com/devfile/kubernetes-api/issues/51 ), che/odo must make a smart kustomize-styled replacement of the image field with built image from the 'dockerfile' component.

```

- composite:
      id: build-and-deploy
      label: Build image and deploy nodejs app
      commands:
      - build-node-app
      - deploy-node-image
      parallel: false
      group: 
          kind: deploy

```
