### ISSUE TITLE
Index server treating paths with double slashes as invalid

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#567]
/kind bug

### Which area this bug is related to?
/area registry

## Bug Summary
Requests to the devfile registry index server with double slashes (such as https://registry.devfile.io//index/all) are treated as invalid by the server and a 404 error code is returned.

Since this could easily happen from a user giving a tool a URL with a slash on the end (assuming the tool just appends the path on to the end), we shouldn't throw an error if this occurs, but return the proper response.

**To Reproduce:**
```
johncollier@jcollier-mac registry-support % curl https://registry.devfile.io//devfiles/java-maven
curl: (6) Could not resolve host: curl
404 page not found
```

## Expected behavior
```
johncollier@jcollier-mac registry-support % curl https://registry.devfile.io//devfiles/java-maven
schemaVersion: 2.0.0
metadata:
  name: java-maven
  version: 1.1.0
  displayName: Maven Java
  description: Upstream Maven and OpenJDK 11
  tags: ["Java", "Maven"]
  projectType: "maven"
  language: "java"
starterProjects:
  - name: springbootproject
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/springboot-ex.git"
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
      memoryLimit: 512Mi
      mountSources: true
      endpoints:
        - name: 'http-8080'
          targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: m2
    volume: {}
commands:
  - id: mvn-package
    exec:
      component: tools
      commandLine: "mvn -Dmaven.repo.local=/home/user/.m2/repository package"
      group:
        kind: build
        isDefault: true
  - id: run 
    exec:
      component: tools
      commandLine: "java -jar target/*.jar"
      group:
        kind: run
        isDefault: true
  - id: debug
    exec:
      component: tools
      commandLine: "java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n -jar target/*.jar"
      group:
        kind: debug
        isDefault: true
```
