### ISSUE TITLE
decouple plugin/tooling declaration from che

### ISSUE THREAD

**Issue by maxandersen** [devfile/api#62]
For me devfile's power is in how it can be used to setup repeated development environments no matter where you run (locally, docker, kubernetes etc.)

Thus I would much prefer to be able for devfile to state in more highlevel form "I would like my ide to be configured to support java with quarkus"  instead of "configure che with java and quarkus". Allowing this would enable other IDE's to get hints and possible direct instructions from the devfile.

i.e. instead of 
```
 components:
      - plugin:
          id: eclipse/che-theia/latest
``` 

which (at least to me) is a hard coupling of not only to che but also to assumption all tooling are done via docker/container plugin I would expect to be able to something like:

```
 components:
      - ide-tooling:
          id: base
          - hints:
                 che:
                        - plugin:
                       id: eclipse/che-theia/latest
        id: java
          - hints:
                 vscode: 
                      - plugin:
                         id: redhat/vs-code/java
                 eclipse:
                     - plugin: 
                           id: org.eclipse.jdt.epp
  
``` 

Above is just suggestion; stuff is missing but just general idea on making the tooling abstraction one level higher to make devfile more universally applicable.
