### ISSUE TITLE
configuration option to avoid unncessary restarts of process

### ISSUE THREAD

**Issue by maxandersen** [devfile/api#64]
Not sure how this fits in with devfile 2.0 spec but it is/was a problem of odo behavior causing a full restart of the running server when files changed - that is not wanted for things like springboot and quarkus.

see odo issue at https://github.com/openshift/odo/pull/3043

**Comment by sbose78** [comment]
Good point, looks like openshift/odo#3043 should be resolving this?

**Comment by maxandersen** [comment]
Yes, 3043 is I understand it odo's approach to support it but not part of the devfile spec.

**Comment by l0rd** [comment]
It's not clear to me how this would translate in the devfile spec. @kadel any idea?

**Comment by kadel** [comment]
> It's not clear to me how this would translate in the devfile spec. @kadel any idea?

I'm not sure. It could be an additional option for exec component. But it might look weird as it make sense only for some type of commands.

This is why we are currently using `attributes` for this.

Would something like this make sense for Che? As far as I know, Che doesn't do any automatic application restarts. The Che user is in control when and if the application process should be restarted.

**Comment by sbose78** [comment]
Yes, options which must not be added as a strongly typed attribute, should go into the loosely typed list of attributes in `attributes`?

**Comment by kadel** [comment]
## Proposal

The commands that get executed can be of two types:

-   **one-shot** command This is a command that does its job and exits. The typical case is build command. Tool executing this command should wait for this command to finish and report its status.
-   **long-running** command This is command is running and doing their job without exiting (like servers). The typical case is run command. The tool should not wait for it to finish. The tool needs to ensure that the command is kept running even when it is not attached to the process.

In addition, the long-running process can be also of two types:

-   hot-reload capable
-   needs to be restarted to pick up changes

This is especially important for debug and run command groups. Some tools like for example odo need to know if the command needs to be restart to pick up changes or not.

This means that we need two additional fields for exec commands. 
- `hotReload: (true|false)`
-  `execType: (oneshot|longrunning)`
    (There are only two values, but string value might be better to leave room for future expansion)


Note that a combination of `execType: oneshot` and `hotRealod: false` doesn't make sense.

Each command group will have different defaults based on its typical use:

-   build
    -   `execType: oneshot`
- run
    -   `execType: longrunning`
    -   `hotReload: true`
-  debug
    -   `execType: longrunning`
    -   `hotReload: true`
- test
    -   `execType: oneshot`
    



### Example
```yaml
commands:
    - exec:
        id: install-deps
        component: dev 
        commandLine: "npm package"
        group:
          kind: build
          isDefault: true
    - exec:
        id: run
        component: dev
        commandLine: "npm run start"
        hotReload: false
        group:
          kind: run
          isDefault: true
    - exec:
        id: run-dev
        component: dev
        commandLine: "npm run debug"
        hotReload: false
        group:
          kind: run
```
