### ISSUE TITLE
devfile/library doesn't reflect additional resource limits

### ISSUE THREAD

**Issue by kadel** [devfile/api#641]
/kind bug

### Which area this bug is related to?

/area library

## What versions of software are you using?

**Operating System:**

**Go Pkg Version:**
devfile/library v1.2.0

## Bug Summary
**Describe the bug:**

Additional resource settings were added in  https://github.com/openshift/odo/issues/5132 

**To Reproduce:**
define container component with 
```
    memoryLimit: 1Gi
    memoryRequest: 1Gi
    cpuRequest: 1m
    cpuLimit: 1m
```
Devfile library translates it to container with only 
```
        resources:
          limits:
            memory: 1Gi
```

memoryRequest, cpuRequest,  cpuLimit are not reflected

## Expected behavior
to have all fields reflected in kubernetes container spec

```
    resources:
      requests:
        memory: "1Gi"
        cpu: "1m"
      limits:
        memory: "1Gi"
        cpu: "1m"
```
