### ISSUE TITLE
devfile/library doesn't reflect `ephemeral` volume setting

### ISSUE THREAD

**Issue by kadel** [devfile/api#642]
/kind bug

### Which area this bug is related to?
/area library

## What versions of software are you using?

**Operating System:**

**Go Pkg Version:**
devfile/library v1.2.0

## Bug Summary

**To Reproduce:**
define ephemeral devfile volume component
```
- name: volume-test
  volume:
    ephemeral: true
```

currently, it will create PVC volume
```
      volumes:
      - name: volume-test-volume
        persistentVolumeClaim:
          claimName: volume-test-pvc
```

## Expected behavior
if `ephemeral: true` the kubernetes volume inside Deployment should be `emptyDir` 
```
      volumes:
      - name: volume-test-volume
        emptyDir: {}
```
