### ISSUE TITLE
Multiple commands of a group should have one isDefault true

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#66]
According to the schema https://github.com/devfile/kubernetes-api/blob/master/schemas/devfile.json#L109; commands belonging to a same group in devfile can have multiple defaults which i think is not right.

For example, currently we can do this:
```
commands:
  - exec:
      id: defaultRun
      component: runtime
      commandLine: "/artifacts/bin/start-server.sh"
      workingDir: /
      group:
        kind: run
        isDefault: true
  - exec:
      id: myRun
      component: runtime
      commandLine: "/artifacts/bin/start-server.sh"
      workingDir: /
      group:
        kind: run
        isDefault: true
```

I think the schema should enforce that only one command can be a default, if there are multiple commands that belong to the same group
