### ISSUE TITLE
Devfiles in the OpenShift Dev Console samples are invalid

### ISSUE THREAD

**Issue by l0rd** [devfile/api#666]
/kind bug
/area registry

## Bug Summary

These 4 OpenShift console samples have a invalid devfile.yaml at their root ([1](https://github.com/redhat-developer/devfile-sample/blob/master/devfile.yaml), [2](https://github.com/elsony/devfile-sample-java-springboot-basic/blob/main/devfile.yaml), [3](https://github.com/elsony/devfile-sample-python-basic/blob/main/devfile.yaml), [4](
https://github.com/elsony/devfile-sample-code-with-quarkus/blob/main/devfile.yaml)):

![image](https://user-images.githubusercontent.com/606959/140045242-1de3b9e7-c240-4958-a72b-8dbde71ca2e7.png)

All have a `buildguidance` container referencing a nonexistent `buildguidanceimage-placeholder`:

```
  - name: buildguidance
    attributes:
      tool: console-import
    container:
      image: buildguidanceimage-placeholder. # <== this image doesn't exist
``` 

As a consequence CRW fails to start the workspaces ([related issue](https://issues.redhat.com/browse/CRW-2411)).

## Additional context

https://github.com/openshift/console/issues/8729
