### ISSUE TITLE
Registry should support stack version from an outside repository

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#788]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**
After https://github.com/devfile/api/issues/735 has been implemented, registry supports stacks & samples with multiple versions. 
Registry should also support stack version from an outside repository, for example:
```
versions:
  - version: 1.0.1
    git:
      url: https://github.com/yangcao77/devfile-multiversion-alterrepo
      subDir: nodejs/1.0.1
      revision: 1.0.1-branch
```

**Detailed description:**
See above

## Describe the solution you'd like

The stack content for that version should be downloaded and cached in registry server when building registry image.
