### ISSUE TITLE
Kubernetes component referencing whole directory

### ISSUE THREAD

**Issue by kadel** [devfile/api#844]
**Which area this feature is related to?**

/area api

## Which functionality do you think we should add?

Allo referencing the whole directory for `kubernetes` component. 

**Why is this needed? Is your feature request related to a problem?**
Currently, If you need to apply multiple k8s resources, you need to define the `kubernetes` component for each file. 
```yaml
components:
- name: resource-app
  kubernetes:
    uri: kubernetes/default/app.yaml

- name: resource-pvc
  kubernetes:
    uri: kubernetes/default/pvc.yaml

- name: resource-service
  kubernetes:
    uri: kubernetes/default/service.yaml

- name: resource-route
  kubernetes:
    uri: kubernetes/local/route.yaml
```

Then define apply command for each kubernetes component
```yaml
commands:
- apply:
    component: resource-app
  id: deploy-app

- apply:
    component: resource-pvc
  id: deploy-pvc

- apply:
    component: resource-service
  id: deploy-service

- apply:
    component: resource-route
  id: deploy-route
```

And only then you can define a composite that will apply all those resources:
```yaml
commands:
- composite:
    commands:
      - deploy-pvc
      - deploy-service
      - deploy-route
      - deploy-app
  id: deploy-k8s
```

This is quite a lot for simply wanting to apply yaml files i a directory. 

**Detailed description:**

## Describe the solution you'd like
Something like `directory` field for `kubernetes` component would be handy. 

```yaml
components:
- name: k8s-resources
  kubernetes:
    directory: kubernetes/default
```
