### ISSUE TITLE
Support for environment variables with `valueFrom.fieldRef.fieldPath` to access pod information

### ISSUE THREAD

**Issue by dkwon17** [devfile/api#853]
**Which area this feature is related to?**

/area api

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**
This feature would be useful if a workspace container needs to know details about the running workspace pod which are not known at the time the devfile is written (e.g. the pod IP, pod namespace etc.)

**Detailed description:**
Kubernetes provides the ability to expose Pod information to containers via environment variables: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/.

## Describe the solution you'd like

Following the link provided above, it would be great if we can provide pod field references to be the values of the environment variables.
For example:
```
...
components:
  - name: mycontainer
    container:
      image: imageurl
      env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
...
```

## Describe alternatives you've considered

An alternative might be to use a kubernetes client from a workspace container to access pod details.
