### ISSUE TITLE
referencing mulitple files in one `kubernetes` component

### ISSUE THREAD

**Issue by kadel** [devfile/api#871]
/area api

## Which functionality do you think we should add?
It should be possible to reference a whole directory or multiple files in one  `kubernetes` component.

**Why is this needed? Is your feature request related to a problem?**

Currently, you can either inline kubernetes resource in devfile or use `uri` that references a single file. 

Problem is that in most cases users will want to reference more than just one existing file. 
This is a common scenario. Real-world applications usually have multiple resources split across files. Managing everything in one big file would be painful. 

**Detailed description:**
Let's say that I want to create a devfile command that applies multiple yaml files.

With the current spec, I need to create a separate `kubernetes` component for each file, then create `apply` command for each component, and then tie everything together with `composite` command. 

```yaml
components:
- name: resource-deployment
  kubernetes:
    uri: kubernetes/deployment.yaml

- name: resource-pvc
  kubernetes:
    uri: kubernetes/pvc.yaml

- name: resource-service
  kubernetes:
    uri: kubernetes/service.yaml

- name: resource-route
  kubernetes:
    uri: kubernetes/route.yaml

commands:
- apply:
    component: resource-deployment
  id: deploy-deployment

- apply:
    component: resource-pvc
  id: deploy-pvc

- apply:
    component: resource-service
  id: deploy-service

- apply:
    component: resource-route
  id: deploy-route

- apply:
    component: app-image
  id: app-image

- composite:
    commands:
      - deploy-pvc
      - deploy-service
      - deploy-route
      - deploy-deployment
    group:
      kind: deploy
  id: deploy
```

You can see that there is a lot of boilerplate and with each new file it will multiply.

## Describe the solution you'd like

I can see two options. 

### Option A: New `dir` field in `kubernetes` component.
```yaml
- name: deploy-resources
  kubernetes:
    dir: kubernetes/
```

### Option B: Changing `uri` to accept a list of URLs

```yaml
- name: deploy-resources
  kubernetes:
    uri: 
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml
      - kubernetes/pvc.yaml
      - kubernetes/route.yaml
```

I think that **Option B** might be better. But problem is that it will be a breaking change in spec.  Alternatively, we could consider naming it `uris` and keep  `uri`  as it is for backward compatibility. "Option A" would be limited referencing only local files in the project directory.

Both options would drastically simply this case. 
The original example would be reduced to 
```yaml
components:
- name: deploy-resources
  kubernetes:
    uris: 
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml
      - kubernetes/pvc.yaml
      - kubernetes/route.yaml

commands:
- apply:
    commands:
      - deploy-resources
    group:
      kind: deploy
  id: deploy
```
