### ISSUE TITLE
File URIs into parent Devfile are not updated when flattened into child Devfile

### ISSUE THREAD

**Issue by feloy** [devfile/api#904]
/kind bug

### Which area this bug is related to?

/area library

## What versions of software are you using?

**Operating System:**

Fedora Linux

**Go Pkg Version:**

`github.com/devfile/library v1.2.1-0.20220602130922-85a4805bd59c`

## Bug Summary
**Describe the bug:**

- Using `ParseDevfileAndValidate` function, with FlattenedDevfile set to true (or true by default)
- When a parent devfile is referenced from the Devfile, and the parent devfile is in another directory
- When the parent Devfile contains a Uri referencing a file relative to the parent Devfile path

The resulting flattened Devfile copies the Uri as is, without taking into account that the parent is not in the same directory as the child Devfile.

**To Reproduce:**

```
$ cat devfile.yaml
schemaVersion: 2.1.0
metadata:
  name: child
parent:
  uri: "../devfile.yaml"

$ cat ../devfile.yaml 
commands:
- exec:
    commandLine: GOCACHE=${PROJECT_SOURCE}/.cache go build main.go
    component: runtime
    group:
      isDefault: true
      kind: build
    workingDir: ${PROJECT_SOURCE}
  id: build
- exec:
    commandLine: ./main
    component: runtime
    group:
      isDefault: true
      kind: run
    workingDir: ${PROJECT_SOURCE}
  id: run
components:
- container:
    endpoints:
    - name: http
      targetPort: 8080
    image: quay.io/devfile/golang:latest
    memoryLimit: 1024Mi
    mountSources: true
  name: runtime
- kubernetes:
    uri: "manifest.yaml"                                     // relative path to referenced file
  name: kube-cmp
metadata:
  name: my-go-app
schemaVersion: 2.1.0
```
The flattened devfile is:

```
commands:
- attributes:
    api.devfile.io/imported-from: 'uri: ../devfile.yaml'
  exec:
    commandLine: GOCACHE=${PROJECT_SOURCE}/.cache go build main.go
    component: runtime
    group:
      isDefault: true
      kind: build
    hotReloadCapable: false
    workingDir: ${PROJECT_SOURCE}
  id: build
- attributes:
    api.devfile.io/imported-from: 'uri: ../devfile.yaml'
  exec:
    commandLine: ./main
    component: runtime
    group:
      isDefault: true
      kind: run
    hotReloadCapable: false
    workingDir: ${PROJECT_SOURCE}
  id: run
components:
- attributes:
    api.devfile.io/imported-from: 'uri: ../devfile.yaml'
  container:
    dedicatedPod: false
    endpoints:
    - name: http
      secure: false
      targetPort: 8080
    image: quay.io/devfile/golang:latest
    memoryLimit: 1024Mi
    mountSources: true
  name: runtime
- attributes:
    api.devfile.io/imported-from: 'uri: ../devfile.yaml'
  kubernetes:
    uri: manifest.yaml                                                    // should be "../manifest.yaml"
  name: kube-cmp
metadata:
  name: child
schemaVersion: 2.1.0
```

## Expected behavior

The URIs inside the parent devfile should be adapted by moving them relative to the child devfile path.
