### ISSUE TITLE
Add inline support for plug-ins

### ISSUE THREAD

**Issue by benoitf** [devfile/api#95]
**Is your feature request related to a problem? Please describe.**
Today, when I create a devfile I can use
```yaml
schemaVersion: 2.0.0
metadata:
  name: nodejs-stack
projects:
  - name: project    
    git:
      location: "https://github.com/che-samples/web-nodejs-sample.git"
components:
  - plugin:
      id: eclipse/che-theia/7.1.0
  - plugin:
      id: eclipse/che-machine-exec-plugin/7.1.0
```

where plugins are referenced by ids

**Describe the solution you'd like**
I would like to be able to inline the content of a plug-in

```yaml
components:
  - plugin:
      id: eclipse/che-theia/7.1.0
  - plugin:
      inline: |
            schemaVersion: 2.0.0
            metadata:
            publisher: redhat
            name: java8
            version: 0.57.0
            displayName: Language Support for Java 8
            title: Language Support for Java(TM) by ...
            description: Java Linting, Intellisense ...
            icon: https://.../logo-eclipseche.svg
            repository: https://github.../vscode-java
            ....
```

**Describe alternatives you've considered**
none

**Additional context**
To be able to easily test plugins or different version of plug-ins without publishing them first
