### ISSUE TITLE
Add more information regarding starterProjects in the devfile spec and in the REST API

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#961]
**Which area this feature is related to?**

/area api
/area registry

## Which functionality do you think we should add?

**Detailed description:**

1. Starter projects should have a display name property. 
2. More information regarding starter projects should be returned using the REST API.

**Why is this needed? Is your feature request related to a problem?**

1. Starter project names displayed on the registry viewer would look nicer.
2. The registry viewer would not need to parse the devfile YAML to access the display name and description properties.

## Describe the solution you'd like

Add a display name property to each starter project.

Devfile Spec Example
```yaml
starterProjects:
  - name: flask-example
    displayName: Flask Example
    description:
      'Flask is a web framework, it’s a Python module that lets you develop web applications easily.
      It’s has a small and easy-to-extend core: it’s a microframework that doesn’t include an ORM (Object Relational Manager) or such features.'
    git:
      remotes:
        origin: https://github.com/devfile-samples/python-ex
```

Return more information regarding starter projects in the REST API

- `name`
- `displayName`
- `description`
- Potentially more fields?

```json
[
  ...
    {
    "name": "python",
    "version": "2.0.1",
    "displayName": "Python",
    ...
    "starterProjects": [
      {
        "name": "flask-example",
        "displayName": "Flask Example",
        "description": "..."
      },
    ],
    "provider": "Red Hat"
  },
  ...
]
```

## Describe alternatives you've considered

N/A

## Additional context

N/A
