### ISSUE TITLE
Clarify on how to use image name in image component and how tools can consume it

### ISSUE THREAD

**Issue by elsony** [devfile/api#985]
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?
/area api

## Issue details
**What mistake did you find / what is missing in the documentation?**
The existing `imageName` field in the image component only has a brief field description. Based on the discussion on the community call on 11/14 (see the recording https://drive.google.com/file/d/1XLTdizST_LeoKpF7xw4Q9k__6LoXKCmo/view?usp=sharing for details), we need to clarify how the imageName field is set and handled by the tools.

Summary of the change:
1. The user can specify the `imageName` with either a full URL or a relative location of the image within an image registry to store the built image.
2. If a relative location is being used, the tools will have their own way to find out the image registry location (e.g. detection or user input). After the image component is built, it will automatically replace the correct image location in memory so that it can be used by an image container or the kubernetes component for deploying the image.
3. If a full URL is used, the tools will not replace it with the automatically generated URL and will use the full URL to store the built image.

**Comment by l0rd** [comment]
Considering the `imageName` as a full registry image has collision and permissions problems. We should avoid that.

We should rather [consider it an image selector as `Tilt` does](https://docs.tilt.dev/dependent_images.html):
> my-image is an image selector. Tilt will scan all your workload manifests for images, and match any object that contains the image name my-image (regardless of tag).

Rephrasing that for `imageName`:

```
imageName is an image selector. Tools will scan all your conatainer and 
kubernetes components for images, and match any object that contains the
image name imageName (regardless of the registry and tag).
```

**example**

```yaml
components:
  - name: devtools-image
    image:
      imageName: devtools
      autoBuild: true
      dockerfile:
        uri: Dockerfile
  - name: devtools
    container:
      image: quay.io/devfile/devtools:ubi8-latest
      memoryLimit: 512Mi
      command: ['sleep', 'infinity']
```

==> imageName `devtools` matches the container image `quay.io/devfile/devtools:ubi8-latest`.
