### ISSUE TITLE
[python stack] Port mismatch

### ISSUE THREAD

**Issue by kadel** [devfile/api#998]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

## Bug Summary
In python 3.0.0 stack [devfile.yaml](https://github.com/devfile/registry/blob/4e7b4782b2a49874cc73ff6537544f71288d2874/stacks/python/3.0.0/devfile.yaml#L33
) has 
```
      endpoints:
        - name: http-python
          targetPort: 8080
```
that matches what is there in [starterProject](https://github.com/devfile-samples/python-ex/blob/f2670f8ca92e6945a81cede96356a1d8ffbb8c9d/app.py#L11)

 

but [kubernetes component] (https://github.com/devfile/registry/blob/4e7b4782b2a49874cc73ff6537544f71288d2874/stacks/python/3.0.0/devfile.yaml#L52) and related stuff  uses 8081

```
  - name: deploy
    kubernetes:
      uri: kubernetes/deploy.yaml
      endpoints:
      - name: http-8081
        targetPort: 8081
```

[Devfiles uses 8081](https://github.com/devfile/registry/blob/4e7b4782b2a49874cc73ff6537544f71288d2874/stacks/python/3.0.0/docker/Dockerfile#L4-L5), [deploy.yaml has also 8081](https://github.com/devfile/registry/blob/4e7b4782b2a49874cc73ff6537544f71288d2874/stacks/python/3.0.0/kubernetes/deploy.yaml#L7-L10)
